pipeline:
  test:
    image: teameow/dockerfiles:drone
    commands:
      # versions
      - printf "%s\n------------------------------\n-------  V E R S I O N -------\n------------------------------%s\n%s\n"
      - php -v
      - git --version
      - composer --version
      - phpunit --version

      # dependencies, tests.
      - printf "%s\n------------------------------\n---------  S T A R T ---------\n------------------------------%s\n%s\n"
      - composer install
      - mkdir -p build/logs
      - git submodule update --init --recursive
      - vendor/bin/phpunit

      # coveralls
      # - printf "%s\n------------------------------\n-----  C O V E R A L L S -----\n------------------------------%s\n%s\n"
      # - coveralls -v -x build/logs/clover.xml
      
